### ISSUE TITLE
error code help me pls

### ISSUE THREAD

**Issue by vanna-code** [kuff/discordify#10]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kuff** [comment]
Hello.

I do not understand what you mean - it seems that you have not filled out the form. I need more information in order to help you.

- What error code are you getting?
- In what context are you getting the error code? (When starting the script, or when trying to play a song, etc.)
- Is the bot starting without errors?
- Have you tried running the test script with `npm run test`?

**Comment by kuff** [comment]
Hello again.

Just a heads up that I'll be closing this issue soon if I do not hear back from you.
